steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/omics-ai-mcp:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/omics-ai-mcp:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'omics-ai-mcp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/omics-ai-mcp:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Substitutions for customization
substitutions:
  _REGION: us-central1

# Build timeout
timeout: '1200s'

# Service account permissions
options:
  logging: CLOUD_LOGGING_ONLY